openapi: 3.0.2
info:
  title: Bottle Bioassays
  description: Bottle bioassay specifications
  contact:
    name: help@calsurv.org
    email: help@calsurv.org
  license:
    name: GNU GPL
    url: http://www.gnu.org/licenses/gpl.html
  version: 1.0.0

paths:
  /bottletests:
    parameters:
      - name: length
        in: query
        description: Number of bottle tests to return
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: Offset from beginning of list where to start gathering bottle tests
        required: false
        schema:
          type: integer
    get:
      operationId: bottle_bioassay.bottle_test.search
      summary: Retrieve bottle tests
      description: Retrieve bottle tests
      responses:
        200:
          description: Successfully retrieved a lost of bottle tests
          headers:
            X-total-count:
              description: The total number of bottle tests
              schema:
                type: integer
                minimum: 0
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/BottleTest'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'


  /bottletests/{id}:
    parameters:
      - name: id
        in: path
        description: Id of the bottle test
        required: true
        schema:
          $ref: '#components/schemas/BottleTest/properties/id'
    get:
      summary: Retrieve a specific bottle test
      description: Retrieve a specific bottle test
      responses:
        200:
          description: Successfully retrieved a specific bottle test
          content:
            application/json:
              schema:
                $ref: '#components/schemas/BottleTest'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /bottletests/{id}/bottles:
    parameters:
      - name: id
        in: path
        description: Id of the bottle test
        required: true
        schema:
          $ref: '#components/schemas/BottleTest/properties/id'
    get:
      operationId: bottle_bioassay.bottle.search
      summary: Retrieve bottles from a specific test
      description: Retrieve bottles from a specific test
      responses:
        200:
          description: Successfully retrieved bottles from a specific bottle test
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Bottle'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /bottletests/{id}/bottles/{bottle_id}:
    parameters:
      - name: id
        in: path
        description: Id of the bottle test
        required: true
        schema:
          $ref: '#components/schemas/BottleTest/properties/id'
      - name: bottle_id
        in: path
        description: Id of the bottle 
        required: true
        schema:
          $ref: '#components/schemas/Bottle/properties/id'
    get:
      summary: Retrieve bottles from a specific test
      description: Retrieve bottles from a specific test
      responses:
        200:
          description: Successfully retrieved bottles from a specific bottle test
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Bottle'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /bottletests/{id}/bottles/{bottle_id}/counts:
    parameters:
      - name: id
        in: path
        description: Id of the bottle test
        required: true
        schema:
          $ref: '#components/schemas/BottleTest/properties/id'
      - name: bottle_id
        in: path
        description: Id of the bottle 
        required: true
        schema:
          $ref: '#components/schemas/Bottle/properties/id'
    get:
      summary: Retrieve bottles from a specific test
      description: Retrieve bottles from a specific test
      responses:
        200:
          description: Successfully retrieved bottles from a specific bottle test
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/BottleCount'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel' 

  /bottletests/{id}/bottles/{bottle_id}/counts/{count_id}:
    parameters:
      - name: id
        in: path
        description: Id of the bottle test
        required: true
        schema:
          $ref: '#components/schemas/BottleTest/properties/id'
      - name: bottle_id
        in: path
        description: Id of the bottle 
        required: true
        schema:
          $ref: '#components/schemas/Bottle/properties/id'
      - name: count_id
        in: path
        description: Id of the count
        required: true
        schema:
          $ref: '#components/schemas/BottleCount/properties/id'
    get:
      summary: Retrieve a specific count
      description: Retrieve a specific count 
      responses:
        200:
          description: Successfully retrieved specific count
          content:
            application/json:
              schema:
                $ref: '#components/schemas/BottleCount'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'          

  /bottles:
    parameters:
      - name: length
        in: query
        description: Number of bottle tests to return
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: Offset from beginning of list where to start gathering bottle tests
        required: false
        schema:
          type: integer
    get:
      operationId: bottle_bioassay.bottle.search
      summary: Retrieve bottle tests
      description: Retrieve bottle tests
      responses:
        200:
          description: Successfully retrieved a lost of bottle tests
          headers:
            X-total-count:
              description: The total number of bottle tests
              schema:
                type: integer
                minimum: 0
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/Bottle'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /bottles/{id}:
    parameters:
      - name: id
        in: path
        description: Id of the bottle test
        required: true
        schema:
          $ref: '#components/schemas/Bottle/properties/id'
    get:
      summary: Retrieve a specific bottle
      description: Retrieve a specific bottle identified by id
      responses:
        200:
          description: Successfully retrieved a bottle test
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Bottle'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /bottles/{id}/counts:
    parameters:
      - name: id
        in: path
        description: Id of the bottle test
        required: true
        schema:
          $ref: '#components/schemas/Bottle/properties/id'
    get:
      summary: Retrieve a specific bottle's counts
      description: Retrieve a specific bottle's count
      responses:
        200:
          description: Successfully retrieved a bottle test's counts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/BottleCount'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /bottles/{id}/counts/{count_id}:
    parameters:
      - name: id
        in: path
        description: Id of the bottle test
        required: true
        schema:
          $ref: '#components/schemas/Bottle/properties/id'
      - name: count_id
        in: path
        description: Id of the bottle count
        required: true
        schema:
          $ref: '#components/schemas/BottleCount/properties/id'
    get:
      summary: Retrieve a specific bottle count
      description: Retrieve a specific bottle count
      responses:
        200:
          description: Successfully retrieved a bottle count
          content:
            application/json:
              schema:
                $ref: '#components/schemas/BottleCount'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /bottlecounts:
    parameters:
      - name: length
        in: query
        description: Number of bottle tests to return
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: Offset from beginning of list where to start gathering bottle tests
        required: false
        schema:
          type: integer
    get:
      summary: Retrieve bottle count
      description: Retrieve bottle tests
      responses:
        200:
          description: Successfully retrieved a lost of bottle tests
          headers:
            X-total-count:
              description: The total number of bottle tests
              schema:
                type: integer
                minimum: 0
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/BottleCount'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /bottlecounts/{id}:
    parameters:
      - name: id
        in: path
        description: Id of the bottle count
        required: true
        schema:
          $ref: '#components/schemas/BottleCount/properties/id'
    get:
      summary: Retrieve a specific bottle count
      description: Retrieve a specific bottle identified by id
      responses:
        200:
          description: Successfully retrieved a bottle test
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Bottle'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    InternalError:
      description: Internal Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'

  schemas:
    ErrorModel:
      type: object
      required:
      - message
      - code
      properties:
        message:
          type: string
          example: "Something went wrong"
        code:
          type: integer
          minimum: 100
          maximum: 600
          example: 500
    ExtendedErrorModel:
      allOf:
      - $ref: '#/components/schemas/ErrorModel'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string

    BottleTest:
      properties:
        id:
          type: integer
          description: Internal identifier
          example: 100
        agency:
          type: string
          pattern: "[A-Za-z0-9]{2,4}-[A-Za-z0-9]{4}"
          description: Agency code for agency that entered this bottle test
          example: CA-DART
        name:
          type: string
          description: Text to briefly describe this bottle test
          example: Cx. quinqs naled test
        date:
          type: string
          format: date
          description: The date this bottle test occurred
          example: 2017-10-31
        material:
          type: string
          description: Chemical used
          example: Naled
        diagnostic_dose:
          type: string
          description: Dosage of chemical used
          example: 2.25 μg/mL
        lot_number: 
          type: string
          description: The lot number the chemical came from
          example: 7467300
        synergist:
          type: string
          description: Synergist used in conjunction with the chemical
          example: PBO
        synergist_dose:
          type: string
          description: Dosage of synergist used
          example: 2.25 μg/mL
        synergist_lot_number:
          type: string
          description: Lot number used for this synergist
          example: 7467300
        control_mortality:
          type: number
          format: double
          description: Percentage of mosquitoes that died from a control group
          example: 22.2
        tested_by:
          type: string
          description: Person performing this bottle test
          example: Jody Simpson
        description:
          type: string
          description: Text notes for this bottle test
          example: Reared from eggs laid in lab
        add_date:
          type: string
          format: date-time
          description: The datetime this record was created
          example: 2018-11-07 08:18:29.930559-08
        bottles:
          type: array
          items:
            $ref: '#components/schemas/Bottle'

    Bottle:
      properties:
        id:
          type: integer
          description: Internal identifier
          example: 100
        bottle_test_id:
          type: integer
          description: Bottle test this bottle belongs to 
          example: 100
        species:
          type: string
          description: Tested species in abbreviated format
          example: Cx quinquefasciatus
        source_type:
          type: string
          description: The source of the tested mosquitoes
          enum: 
            - 'field'
            - 'colony'
          example: colony
        generation:
          type: integer
          description: F generation these mosquitoes belong to.  Only applicable if source_type is field.
          example: 0
          minimum: 0
        latitude:
          type: number
          format: double
          description: Longitude this mosquito was collected from. Only applicable if source_type is field.
          example: 38.5816
        longitude:
          type: number
          format: double
          description: Longitude this mosquito was collected from. Only applicable if source_type is field.
          example: 121.4944
        colony:
          type: string
          description: The name of this colony.  Only applicable if source_type is colony.
          example: CQ1
        num_tested:
          type: integer
          minimum: 0
          example: 30          
        add_date:
          type: string
          format: date-time
          description: The datetime this record was created
          example: 2018-11-07 08:18:29.930559-08
        counts:
          type: array
          items:
            $ref: '#components/schemas/BottleCount'

    BottleCount:
      properties:
        id:
          type: integer
          description: Internal identifier
          example: 100
        bottle_id:
          type: integer
          description: The bottle id this count belongs to
          example: 100
        exposure_length:
          type: integer
          description: The time in minutes of this reading
          minimum: 0
          example: 120
        survival_count:
          type: integer
          description: The number of mosquitoes alive at this reading
          example: 17
        add_date:
          type: string
          format: date-time
          description: The datetime this record was created
          example: 2018-11-07 08:18:29.930559-08